[package]
name = "ale-env"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.70.1"
cmake = "0.1.52"

[dependencies]
tempdir = "0.3.7"

[dev-dependencies]
image = "0.25.5"
rand = "0.8.5"
